apiVersion: apps/v1
kind: Deployment
metadata:
  name: loan-service
spec:
  replicas: 2
  selector:
    matchLabels:
      app: loan-service
  template:
    metadata:
      labels:
        app: loan-service
    spec:
      containers:
        - name: loan-service
          image: gcr.io/libraryproject-447217/loan-service:v1
          ports:
            - containerPort: 8080
          env:
            - name: SPRING_DATASOURCE_URL
              value: jdbc:mysql://mysql-loan-service:3306/loan
            - name: SPRING_DATASOURCE_USERNAME
              value: root
            - name: SPRING_DATASOURCE_PASSWORD
              value: Password
            - name: SPRING_RABBITMQ_ADDRESSES
              value: amqp://rabbitmq-service:5672
---
apiVersion: v1
kind: Service
metadata:
  name: loan-service
spec:
  type: LoadBalancer
  selector:
    app: loan-service
  ports:
    - port: 8080
      targetPort: 8080
