apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mysql-loan-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql-loan
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mysql-loan
  template:
    metadata:
      labels:
        app: mysql-loan
    spec:
      containers:
        - name: mysql
          image: mysql:latest
          ports:
            - containerPort: 3306
          env:
            - name: MYSQL_DATABASE
              value: loan
            - name: MYSQL_ROOT_PASSWORD
              value: Password
          volumeMounts:
            - name: mysql-loan-data
              mountPath: /var/lib/mysql
          readinessProbe:
            exec:
              command: ["mysqladmin", "ping", "-h", "localhost"]
            initialDelaySeconds: 10
            periodSeconds: 5
      volumes:
        - name: mysql-loan-data
          persistentVolumeClaim:
            claimName: mysql-loan-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: mysql-loan-service
spec:
  ports:
    - port: 3306
      targetPort: 3306
  selector:
    app: mysql-loan
